[[prerequisites]]
== Prerequisites

//[[technical_requirements]]
=== Technical requirements

* *Limit increases for F1 instances*. {partner-product-short-name} runs on https://aws.amazon.com/ec2/instance-types/f1/[Amazon EC2 F1 instances^] because it requires a field-programmable gate array (FPGA).
This Quick Start supports `f1.2xlarge`, `f1.4xlarge`, and `f1.16xlarge` instance types. You should request limit increases for F1 instances, to support the maximum number of simultaneous DRAGEN jobs that you expect to run.
* *S3 bucket for genomic data*. You must have an Amazon Simple Storage Service (Amazon S3) bucket in the AWS Region where you plan to deploy the Quick Start. This S3 bucket should contain:
+
  ** The genomic input datasets that you want to run in the Quick Start environment
  ** The {partner-product-short-name}-specific reference hash table directories that are provided by {partner-company-name} or that you create from FASTA files. For instructions on how to create reference hash table directories, refer to https://support-docs.illumina.com/SW/DRAGEN_v38/Content/SW/DRAGEN/RefGenIntro_fDG.htm[DRAGEN Bio-IT Platform User Guide^]
  ** An output folder for {partner-product-short-name} job outputs such as the binary alignment map (BAM) and variant call format (VCF) files
+
You’ll be prompted for the bucket name when you deploy the Quick Start. The appropriate roles and policies to read from, and write to, this S3 genomics bucket are created during the Quick Start deployment.
