---
AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation Template creates the ECR Repository and Artifact
  Bucket for the Docker Pipeline. Modified from
  https://github.com/aws-quickstart/saas-identity-cognito/blob/master/templates/docker-bucket-repository.yaml
Resources:
  Dragen:
    Type: AWS::ECR::Repository
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
Outputs:
  ArtifactBucket:
    Value: !Ref ArtifactBucket
  Repository:
    Value: !Ref Dragen
