---
AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation Template creates the ECR Repository and Artifact
  Bucket for the Docker Pipeline. (qs-1s1cul5im)
Metadata:
  cfn-lint: { config: { ignore_checks: [W9006, W9002, W9003, W3011] } }
Resources:
  Dragen:
    Type: AWS::ECR::Repository
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
Outputs:
  ArtifactBucket:
    Value: !Ref ArtifactBucket
  Repository:
    Value: !Ref Dragen
