AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys an environment to run Edico Genome's DRAGEN software using AWS Batch. (qs-1oqea624b)

Metadata:
  AWSAMIRegionMap:
    Filters:
      DRAGEN:
        owner-alias: aws-marketplace
        product-code: 9uotaksivr7km6tn0wa0sy2fw
        product-code.type: marketplace
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPCID
      - PrivateSubnet1ID
      - PrivateSubnet2ID
    - Label:
        default: DRAGEN Quick Start Configuration
      Parameters:
      - KeyPairName
      - InstanceType
      - BidPercentage
      - MinvCpus
      - MaxvCpus
      - DesiredvCpus
      - GenomicsS3Bucket
      - RetryNumber
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      KeyPairName:
        default: Key Pair Name
      PrivateSubnet1ID:
        default: Private Subnet 1 ID
      PrivateSubnet2ID:
        default: Private Subnet 2 ID
      VPCID:
        default: VPC ID
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      InstanceType:
        default: Instance Type
      BidPercentage:
        default: Spot Bid Percentage
      RetryNumber:
        default: AWS Batch Retry Number
      MinvCpus:
        default: Min vCPUs
      MaxvCpus:
        default: Max vCPUs
      DesiredvCpus:
        default: Desired vCPUs
      GenomicsS3Bucket:
        default: Genomics Data Bucket

Mappings:
  AWSAMIRegionMap:
    AMI:
      DRAGEN: dragen-completesuite-*
    us-east-1:
      DRAGEN: ami-0e33c66ac96a8bee4
    us-west-2:
      DRAGEN: ami-009e3239aa413c21d
    eu-west-1:
      DRAGEN: ami-0ff60dffe92e389e2

Parameters:
  InstanceType:
    Type: String
    Description: Amazon EC2 instance type. DRAGEN requires an FPGA to run, so the instance type must be in the F1 instance family.
    Default: f1.2xlarge
    AllowedValues:
    - f1.2xlarge
    - f1.4xlarge
    - f1.16xlarge
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: The ID of your existing VPC (e.g., vpc-0343606e).
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the private subnet in Availability Zone 1 in your existing VPC (e.g., subnet-a0246dcd).
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the private subnet in Availability Zone 2 in your existing VPC (e.g., subnet-b58c3d67).
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and a forward slash (/) at the end of the prefix.
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Default: quickstart-illumina-dragen/
    Type: String
  KeyPairName:
    Description: The name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  BidPercentage:
    AllowedPattern: (?:\b|-)([1-9]{1,2}[0]?|100)\b
    ConstraintDescription: Spot Bid Percentage should be between 1 and 100, inclusive
    Description: The bid percentage set for your AWS Batch Managed Compute Environment with Spot Instances.
    Default: 50
    Type: String
  RetryNumber:
    AllowedPattern: (?:\b|-)([1-9]|10)\b
    ConstraintDescription: AWS Batch job retry number should be between 1 and 10
    Description: Retry number for an AWS Batch job
    Default: 1
    Type: String
  MinvCpus:
    AllowedPattern: ^(0|[1-9][0-9]{0,2}|1000)$
    ConstraintDescription: Valid between 0 and 1000, inclusive
    Description: Minimum vCPUs for your AWS Batch Compute Environment. Recommend 0.
    Default: 0
    Type: String
  MaxvCpus:
    AllowedPattern: ^(0|[1-9][0-9]{0,2}|1000)$
    ConstraintDescription: Valid between 0 and 1000, inclusive
    Description: Maximum vCPUs for your AWS Batch Compute Environment
    Type: String
  DesiredvCpus:
    AllowedPattern: ^(0|[1-9][0-9]{0,2}|1000)$
    ConstraintDescription: Valid between 1 and 1000, inclusive
    Description: Desired vCPUs for your AWS Batch Compute Environment. Recommend the same number as MinvCpus for cost-optimization.
    Default: 0
    Type: String
  GenomicsS3Bucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: S3 genomics bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: S3 bucket name for the bucket to which you'll read and write genomics data. 
    Type: String

Rules:
  KeyPairsNotEmpty:
    Assertions:
    - Assert:
        !Not
        - Fn::EachMemberEquals:
          - Fn::RefAll: AWS::EC2::KeyPair::KeyName
          - ''
      AssertDescription: All key pair parameters must not be empty
  SubnetsInVPC:
    Assertions:
    - Assert:
        Fn::EachMemberIn:
        - Fn::ValueOfAll:
          - AWS::EC2::Subnet::Id
          - VpcId
        - Fn::RefAll: AWS::EC2::VPC::Id
      AssertDescription: All subnets must be in the VPC
  DRAGENSupportedRegionRule:
    Assertions:
    - Assert:
        Fn::Contains:
        - - us-east-1
          - us-west-2
          - eu-west-1
        - !Ref AWS::Region
      AssertDescription: This Quick Start utilizes DRAGEN Marketplace AMI which is only available
        in the US East (N. Virginia), US West (Oregon), EU (Ireland) regions. Please launch the stack in one of these
        regions to continue.

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources:
  DockerBucketRepository:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/docker-bucket-repository.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]

  CopyFiles:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - DockerBucketRepository
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/copy.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
        DestinationBucket: !GetAtt DockerBucketRepository.Outputs.ArtifactBucket

  WaitHandleContainerBuild:
    Type: AWS::CloudFormation::WaitConditionHandle

  ContainerBuild:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - CopyFiles
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/container-build.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        ArtifactBucket: !GetAtt DockerBucketRepository.Outputs.ArtifactBucket
        ArtifactKey: !Ref QSS3KeyPrefix
        ServiceName: dragen
        Repository: !GetAtt DockerBucketRepository.Outputs.Repository
        WaitHandle: !Ref WaitHandleContainerBuild

  WaitConditionContainerBuild:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn:
    - ContainerBuild
    Properties:
      Handle:
        Ref: WaitHandleContainerBuild
      Timeout: '3600'
      Count: '1'

  Batch:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - ContainerBuild
    - WaitConditionContainerBuild
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/batch.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        GenomicsS3Bucket: !Ref GenomicsS3Bucket
        DragenDockerImage: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${DockerBucketRepository.Outputs.Repository}:dragen
        VpcId: !Ref VPCID
        SubnetIds: !Sub "${PrivateSubnet1ID}, ${PrivateSubnet2ID}"
        BidPercentage: !Ref BidPercentage
        InstanceType: !Ref InstanceType
        ImageId: !FindInMap [ AWSAMIRegionMap, !Ref "AWS::Region", DRAGEN ]
        Ec2KeyPair: !Ref KeyPairName
        MinvCpus: !Ref MinvCpus
        MaxvCpus: !Ref MaxvCpus
        DesiredvCpus: !Ref DesiredvCpus

  CleanupRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ConfigPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Sid: Logging
            Effect: Allow
            Action: logs:*
            Resource: '*'
          - Sid: ECR
            Effect: Allow
            Action: ecr:*
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${DockerBucketRepository.Outputs.Repository}
          - Sid: S3Bucket
            Effect: Allow
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${DockerBucketRepository.Outputs.ArtifactBucket}
          - Sid: S3Object
            Effect: Allow
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${DockerBucketRepository.Outputs.ArtifactBucket}/*

  ContainerCleanup:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - CleanupRole
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/clean-bucket-repository.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        Bucket: !GetAtt DockerBucketRepository.Outputs.ArtifactBucket
        Repository: !GetAtt DockerBucketRepository.Outputs.Repository
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
        RoleArn: !GetAtt CleanupRole.Arn

Outputs:
  DragenJobDefinition:
    Description: The AWS Batch Job Definition for DRAGEN
    Value: !GetAtt Batch.Outputs.DragenJobDefinition
  JobQueue:
    Description: The Job Queue to submit jobs to
    Value: !GetAtt Batch.Outputs.JobQueue
  DragenComputeEnvironmentSpot:
    Value: !GetAtt Batch.Outputs.DragenComputeEnvironmentSpot
  DragenComputeEnvironmentOnDemand:
    Value: !GetAtt Batch.Outputs.DragenComputeEnvironmentOnDemand